image: node:current-alpine3.19

stages:
  - test
  - deploy
  - rebuild

variables:
  APP_NAME: personal

test:
  stage: test
  script:
    - yarn
    - yarn run lint
    - yarn run check
  only:
    - main

dokku-deploy:
  stage: deploy
  before_script:
    - apk update
    - apk add openssh-client git
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - if git remote | grep dokku; then git remote remove dokku; fi
    - git remote add dokku dokku@$DOKKU_HOST:personal
    - git config --global core.sshCommand "ssh -o StrictHostKeyChecking=no"
    - git push dokku HEAD:main
  only:
    - main

dokku-rebuild:
  stage: rebuild
  before_script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no dokku@100.91.27.125 dokku ps:rebuild personal
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
